#!/bin/bash

if [ -d "/home" ]; then
    if ! [ -z "$(ls -A /home)" ]; then
        user=""
        for i in /home/*
        do
            if [ -d "$i/.config/Thunar" ]; then
                mv -fv "$i/.config/Thunar" "$i/.config/Thunar-old-$((1 + $RANDOM % 10000))"
                user=`basename $i`
                cp -r "/etc/xdg/pardus/Thunar" "$i/.config/"
                chown -Rv $user:$user "$i/.config/Thunar"
            fi
        done
    fi
fi
